insert into student(id, firstname, lastname, email_address) values(11, 'Leo', 'Messi', 'leomessi@football.com')
insert into student(id, firstname, lastname, email_address) values(12, 'Cristiano', 'Ronaldo', 'crisRonaldo@football.com')
insert into student(id, firstname, lastname, email_address) values(13, 'Neymar', 'Jr', 'neymarjr@football.com')
insert into student(id, firstname, lastname, email_address) values(14, 'Luis', 'Suarez', 'luisSuarez@football.com')
insert into student(id, firstname, lastname, email_address) values(15, 'Angel Di', 'Maria', 'mariaangel@football.com')